In [1]:
import pandas as pd
import numpy as np
import random

from datetime import datetime, timedelta

In [2]:
random.seed(42)
np.random.seed(42)

In [3]:
departments = {
    "Public Works": [
        "Pothole Repair",
        "Road Damage",
        "Sidewalk Damage",
        "Snow Removal"
    ],

    "Parks and Recreation": [
        "Tree Maintenance",
        "Park Equipment Damage",
        "Grass Cutting",
        "Trail Maintenance"
    ],

    "Waste Management": [
        "Missed Garbage Pickup",
        "Recycling Issue",
        "Illegal Dumping",
        "Green Bin Issue"
    ],

    "Water Services": [
        "Water Leak",
        "Low Water Pressure",
        "Sewer Backup",
        "Water Quality Concern"
    ],

    "By-law Enforcement": [
        "Noise Complaint",
        "Property Standards",
        "Parking Complaint",
        "Animal Complaint"
    ],

    "Transportation Services": [
        "Streetlight Repair",
        "Traffic Signal Issue",
        "Road Sign Damage",
        "Traffic Concern"
    ]
}

wards = [
    "Ward 1",
    "Ward 2",
    "Ward 3",
    "Ward 4",
    "Ward 5"
]

priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

statuses = [
    "Closed",
    "Open",
    "In Progress"
]

channels = [
    "Web",
    "Phone",
    "Mobile App",
    "Email",
    "In Person"
]

In [4]:
records = []

start_date = datetime(2025, 1, 1)

for request_number in range(1, 2001):

    department = random.choice(list(departments.keys()))

    request_type = random.choice(
        departments[department]
    )

    priority = random.choices(
        priorities,
        weights=[25, 45, 24, 6],
        k=1
    )[0]

    status = random.choices(
        statuses,
        weights=[74, 12, 14],
        k=1
    )[0]

    date_opened = start_date + timedelta(
        days=random.randint(0, 364)
    )

    if status == "Closed":

        resolution_ranges = {
            "Low": (3, 15),
            "Medium": (2, 10),
            "High": (1, 7),
            "Critical": (0, 3)
        }

        minimum_days, maximum_days = resolution_ranges[priority]

        resolution_days = random.randint(
            minimum_days,
            maximum_days
        )

        date_closed = date_opened + timedelta(
            days=resolution_days
        )

        citizen_satisfaction = random.choices(
            [1, 2, 3, 4, 5],
            weights=[4, 7, 18, 37, 34],
            k=1
        )[0]

    else:

        resolution_days = np.nan
        date_closed = pd.NaT
        citizen_satisfaction = np.nan

    target_days = {
        "Low": 14,
        "Medium": 10,
        "High": 7,
        "Critical": 3
    }[priority]

    if status == "Closed":

        if resolution_days <= target_days:
            resolved_within_target = "Yes"
        else:
            resolved_within_target = "No"

    else:

        resolved_within_target = "Pending"

    record = {
        "Request ID": f"SR-2025-{request_number:05d}",
        "Department": department,
        "Request Type": request_type,
        "Priority": priority,
        "Status": status,
        "Ward": random.choice(wards),
        "Date Opened": date_opened,
        "Date Closed": date_closed,
        "Channel": random.choice(channels),
        "Citizen Satisfaction": citizen_satisfaction,
        "Resolution Days": resolution_days,
        "Target Days": target_days,
        "Resolved Within Target": resolved_within_target
    }

    records.append(record)

In [5]:
municipal_df = pd.DataFrame(records)

municipal_df.head()

,Request ID,Department,Request Type,Priority,Status,Ward,Date Opened,Date Closed,Channel,Citizen Satisfaction,Resolution Days,Target Days,Resolved Within Target
0,SR-2025-00001,Transportation Services,Streetlight Repair,Low,Closed,Ward 5,2025-04-25,2025-04-30,Web,5.0,5.0,14,Yes
1,SR-2025-00002,By-law Enforcement,Animal Complaint,Low,Closed,Ward 5,2025-04-30,2025-05-11,Phone,4.0,11.0,14,Yes
2,SR-2025-00003,Transportation Services,Traffic Concern,Low,Closed,Ward 4,2025-01-04,2025-01-19,Mobile App,5.0,15.0,14,No
3,SR-2025-00004,Waste Management,Recycling Issue,Low,Open,Ward 1,2025-02-22,NaT,Email,NaN,NaN,14,Pending
4,SR-2025-00005,Public Works,Sidewalk Damage,High,Closed,Ward 1,2025-01-23,2025-01-29,Email,4.0,6.0,7,Yes

In [6]:
municipal_df["Opened Month"] = (
    municipal_df["Date Opened"]
    .dt.to_period("M")
    .astype(str)
)

municipal_df["Opened Year"] = (
    municipal_df["Date Opened"]
    .dt.year
)

municipal_df["Opened Quarter"] = (
    municipal_df["Date Opened"]
    .dt.quarter
)

municipal_df["Is Closed"] = np.where(
    municipal_df["Status"] == "Closed",
    "Yes",
    "No"
)

municipal_df.head()

,Request ID,Department,Request Type,Priority,Status,Ward,Date Opened,Date Closed,Channel,Citizen Satisfaction,Resolution Days,Target Days,Resolved Within Target,Opened Month,Opened Year,Opened Quarter,Is Closed
0,SR-2025-00001,Transportation Services,Streetlight Repair,Low,Closed,Ward 5,2025-04-25,2025-04-30,Web,5.0,5.0,14,Yes,2025-04,2025,2,Yes
1,SR-2025-00002,By-law Enforcement,Animal Complaint,Low,Closed,Ward 5,2025-04-30,2025-05-11,Phone,4.0,11.0,14,Yes,2025-04,2025,2,Yes
2,SR-2025-00003,Transportation Services,Traffic Concern,Low,Closed,Ward 4,2025-01-04,2025-01-19,Mobile App,5.0,15.0,14,No,2025-01,2025,1,Yes
3,SR-2025-00004,Waste Management,Recycling Issue,Low,Open,Ward 1,2025-02-22,NaT,Email,NaN,NaN,14,Pending,2025-02,2025,1,No
4,SR-2025-00005,Public Works,Sidewalk Damage,High,Closed,Ward 1,2025-01-23,2025-01-29,Email,4.0,6.0,7,Yes,2025-01,2025,1,Yes

In [7]:
print("Rows:", municipal_df.shape[0])
print("Columns:", municipal_df.shape[1])

print("\nMissing Values:")
print(municipal_df.isnull().sum())

print("\nStatus Counts:")
print(municipal_df["Status"].value_counts())

print("\nDepartment Counts:")
print(municipal_df["Department"].value_counts())

Rows: 2000
Columns: 17

Missing Values:
Request ID                  0
Department                  0
Request Type                0
Priority                    0
Status                      0
Ward                        0
Date Opened                 0
Date Closed               506
Channel                     0
Citizen Satisfaction      506
Resolution Days           506
Target Days                 0
Resolved Within Target      0
Opened Month                0
Opened Year                 0
Opened Quarter              0
Is Closed                   0
dtype: int64

Status Counts:
Status
Closed         1494
In Progress     267
Open            239
Name: count, dtype: int64

Department Counts:
Department
Water Services             377
Parks and Recreation       344
By-law Enforcement         333
Transportation Services    323
Public Works               312
Waste Management           311
Name: count, dtype: int64

In [8]:
municipal_df["Date Opened"] = (
    municipal_df["Date Opened"]
    .dt.strftime("%Y-%m-%d")
)

municipal_df["Date Closed"] = (
    pd.to_datetime(municipal_df["Date Closed"])
    .dt.strftime("%Y-%m-%d")
)

In [9]:
file_name = "municipal_service_requests_clean.csv"

municipal_df.to_csv(
    file_name,
    index=False
)

print("Dataset successfully created:", file_name)

Dataset successfully created: municipal_service_requests_clean.csv

In [10]:
from google.colab import files

files.download(
    "municipal_service_requests_clean.csv"
)